<?php

namespace Tests\Feature\Deployment;

use App\Domains\Payments\Models\Payment;
use App\Domains\Security\Services\PermissionRegistry;
use App\Models\User;
use Database\Seeders\RolesAndPermissionsSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Illuminate\Testing\TestResponse;
use Tests\TestCase;

/**
 * BLK-2: signed URLs must survive TLS terminating somewhere else.
 *
 * THE FAILURE THIS PREVENTS CANNOT HAPPEN ON A DEVELOPER'S MACHINE. Every
 * signed URL is an HMAC over the FULL address INCLUDING THE SCHEME. The
 * renewal payment link, the password reset and the email verification link are
 * generated by the scheduler or the queue, where there is no request at all
 * and the address comes from `APP_URL` — so they are always `https://`. They
 * are then validated against what the INCOMING request appears to be, and
 * behind Cloudflare or nginx that is the plain HTTP hop unless the proxy is
 * trusted. The signature does not match, and a perfectly valid link returns a
 * bare 403. The first person to find it is a customer trying to pay.
 *
 * SO EVERY REQUEST HERE IS THE PLAIN HTTP HOP, exactly as PHP receives it
 * behind a proxy, carrying the `X-Forwarded-Proto: https` the proxy adds. Not
 * `HTTPS=on` — setting that would make the request secure on its own and the
 * suite would pass with the fix removed, which is the definition of a
 * decorative gate.
 */
class SignedUrlsBehindProxyTest extends TestCase
{
    use RefreshDatabase;

    /** The headers a TLS-terminating proxy actually adds. */
    private const PROXY = [
        'X-Forwarded-Proto' => 'https',
        'X-Forwarded-For' => '203.0.113.7',
        'X-Forwarded-Host' => 'aziv.example',
        'X-Forwarded-Port' => '443',
    ];

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(RolesAndPermissionsSeeder::class);

        // A production-shaped configuration: the application's own address is
        // https, which is what the scheduler and the queue sign against.
        config(['app.url' => 'https://aziv.example']);
        URL::forceRootUrl('https://aziv.example');
        URL::forceScheme('https');
    }

    private function customer(): User
    {
        $user = User::factory()->create();
        $user->assignRole(PermissionRegistry::CUSTOMER);

        return $user->fresh();
    }

    /**
     * Fetch an https link the way a proxied server receives it.
     *
     * The scheme is knocked down to http — that IS the hop PHP sees — and the
     * forwarded headers are the only evidence that the customer's connection
     * was secure. Trusting them is the entire fix.
     */
    private function throughProxy(string $link): TestResponse
    {
        return $this->withHeaders(self::PROXY)
            ->get('http://'.Str::after($link, 'https://'));
    }

    // -- the mechanism --------------------------------------------------------

    public function test_the_application_trusts_a_proxy_when_one_is_configured(): void
    {
        // Configuration, not a constant: `*` is right behind Cloudflare, a
        // named range is better where one exists, and trusting nothing is
        // right on a server with no proxy at all.
        $bootstrap = file_get_contents(base_path('bootstrap/app.php'));

        $this->assertStringContainsString('trustProxies', $bootstrap,
            'Nothing trusts a proxy, so every emailed link 403s behind one.');
        $this->assertStringContainsString('TRUSTED_PROXIES', $bootstrap,
            'The proxy list must come from the environment, not be hard-coded.');
        $this->assertStringContainsString('HEADER_X_FORWARDED_PROTO', $bootstrap,
            'Without the proto header the scheme is still wrong and signatures still fail.');
    }

    public function test_a_forwarded_request_is_seen_as_secure_only_when_the_proxy_is_trusted(): void
    {
        $request = Request::create('http://aziv.example/renew/abc', 'GET', server: [
            'HTTP_X_FORWARDED_PROTO' => 'https',
            'REMOTE_ADDR' => '10.0.0.5',
        ]);

        Request::setTrustedProxies(['10.0.0.5'], Request::HEADER_X_FORWARDED_PROTO);

        $this->assertTrue($request->isSecure());
        $this->assertSame('https://aziv.example/renew/abc', $request->url());

        // This is the whole bug in one assertion: untrusted, the same request
        // is http, and every signature computed over https fails against it.
        Request::setTrustedProxies([], 0);

        $this->assertFalse($request->isSecure());
        $this->assertSame('http://aziv.example/renew/abc', $request->url());
    }

    // -- the three links that break -------------------------------------------

    public function test_an_email_verification_link_validates_behind_a_proxy(): void
    {
        $user = $this->customer();
        $user->forceFill(['email_verified_at' => null])->save();

        $link = URL::temporarySignedRoute('verification.verify', now()->addHour(), [
            'id' => $user->getKey(),
            'hash' => sha1($user->email),
        ]);

        $this->assertStringStartsWith('https://', $link);

        $response = $this->actingAs($user)->throughProxy($link);

        // Anything but a 403 means the signature was accepted.
        $this->assertNotSame(403, $response->getStatusCode(),
            'A valid verification link was refused — the signature did not survive the proxy.');
        $this->assertNotNull($user->fresh()->email_verified_at,
            'The address was never verified, so the link did not do its job.');
    }

    public function test_a_password_reset_link_validates_behind_a_proxy(): void
    {
        $user = $this->customer();
        $token = app('auth.password.broker')->createToken($user);

        $this->throughProxy(route('password.reset', ['token' => $token]))->assertOk();
    }

    public function test_a_renewal_payment_link_validates_behind_a_proxy(): void
    {
        // The renewal link is the one that costs money when it fails: it is
        // generated by the SCHEDULER, where there is no request at all, and
        // mailed to somebody who is not signed in. A REAL payment, so the page
        // actually renders — pointing the link at a uuid that does not exist
        // would 404 before the signature was ever checked, and the assertion
        // would pass whether the fix worked or not.
        $payment = $this->renewalPayment();

        $link = URL::temporarySignedRoute('renewal.show', now()->addDays(30), ['payment' => $payment->uuid]);

        $this->assertStringStartsWith('https://', $link);

        $this->throughProxy($link)->assertOk();
    }

    // -- trusting a proxy must not weaken the signature -----------------------

    public function test_a_tampered_link_is_still_refused_behind_a_proxy(): void
    {
        // BOTH payments exist: route-model binding runs before the signed
        // middleware, so a made-up uuid would 404 and prove nothing.
        $signed = $this->renewalPayment();
        $other = $this->renewalPayment();

        $link = URL::temporarySignedRoute('renewal.show', now()->addDay(), ['payment' => $signed->uuid]);

        $this->throughProxy(str_replace($signed->uuid, $other->uuid, $link))->assertForbidden();
    }

    public function test_an_expired_link_is_still_refused_behind_a_proxy(): void
    {
        $payment = $this->renewalPayment();

        $link = URL::temporarySignedRoute('renewal.show', now()->addMinute(), ['payment' => $payment->uuid]);

        $this->travelTo(now()->addHour());

        $this->throughProxy($link)->assertForbidden();
    }

    /**
     * A renewal payment with nothing on it but the facts the page needs.
     *
     * No gateway, no invoice, no plan: this suite is about a signature
     * surviving a proxy, and the fewer moving parts stand between the request
     * and that answer, the more the answer is worth.
     */
    private function renewalPayment(): Payment
    {
        return Payment::create([
            'user_id' => $this->customer()->getKey(),
            'purpose' => Payment::PURPOSE_RENEWAL,
            'presentment_amount' => 999,
            'presentment_currency' => 'INR',
            'status' => Payment::STATUS_CREATED,
            'idempotency_key' => 'proxy-'.Str::random(16),
        ]);
    }
}
